### ISSUE TITLE
output of test_pose is not good

### ISSUE THREAD

**Issue by lvjin-alpha** [guangmingw/DOPlearning#4]
Hello, thanks for your codes. 
I used your pretrained model for test_pose. but it does not performed well. 

![Uploading sequences09_pretrained.png…]()
I use evo to evaluate the trajectory. the "gt" is sample['poses'] in test_pose.py line 91, and the "predictions" is your output. (cause both they are relative transform, I manually converted them into absolute transform.)

So I train the model according to your tutorial. But it goes worse after 2000 epochs.
I do not know why. Do you have some output of the posenet? Or can you give me some advise.

你好，感谢你分享代码。
我用你提供的model跑test_pose，但是画出来的轨迹表现很不好。（我在kitti_odometry的各个sequences上都试了下）
我使用evo工具来绘制轨迹。由于代码的输出是相对变换，我手动将test_pose.py第91行的predictions 和sample['poses']转换成绝对变换来绘制，他们的变化方式相同，因此应该不是这里有问题。
然后我打算自己训练，按照你提供的参数，只修改了路径。但是即使2000 epochs之后，跑出来的轨迹还是有问题。
我不知道是不是我的操作有问题，能否看一下你的posenet输出的可视化结果，又或者你能给我一些别的帮助。

**Comment by lvjin-alpha** [comment]
![sequences09_pretrained](https://user-images.githubusercontent.com/30590441/97438867-5f381d80-1960-11eb-8bde-1430b73975f2.png)

**Comment by guangmingw** [comment]
You can check if you align the scale of pose with ground truth. Like depth estimation, the scale of estimated pose is not sure because of the unsupervised method from monocular video.
