### ISSUE TITLE
test_flow.py TypeError: zeros_like(): argument 'input' (position 1) must be Tensor, not list

### ISSUE THREAD

**Issue by songwenhuang** [guangmingw/DOPlearning#5]
Hi,

When running test_flow.py, I got the following error:

Traceback (most recent call last):
  File "test_flow.py", line 396, in <module>
    main()
  File "test_flow.py", line 160, in main
    rigidity_mask_fwd = torch.zeros_like(rigidity_mask_fwd)
TypeError: zeros_like(): argument 'input' (position 1) must be Tensor, not list

Is there any way to fix the error? Thanks.

**Comment by zhangciiiii** [comment]
Try to modify line 160 to：
```
rigidity_mask_fwd = torch.zeros_like(rigidity_mask_fwd([0])
```

> Hi,
> 
> When running test_flow.py, I got the following error:
> 
> Traceback (most recent call last):
> File "test_flow.py", line 396, in
> main()
> File "test_flow.py", line 160, in main
> rigidity_mask_fwd = torch.zeros_like(rigidity_mask_fwd)
> TypeError: zeros_like(): argument 'input' (position 1) must be Tensor, not list
> 
> Is there any way to fix the error? Thanks.
