### ISSUE TITLE
how to train flownet

### ISSUE THREAD

**Issue by lvjin-alpha** [guangmingw/DOPlearning#6]
hello, after training posenet and dispnet by the command in readme. how to train the flownet?

there are 7 losses in train.py but the command in readme just used w1 and w3, how to use other losses, is their performance not good enough?

**Comment by zhangciiiii** [comment]
> hello, after training posenet and dispnet by the command in readme. how to train the flownet?
> 
> there are 7 losses in train.py but the command in readme just used w1 and w3, how to use other losses, is their performance not good enough?

In train.py, the default value of the weight for each loss functions are 0, so when training the flownet, other loss functions are not used. Thats because some loss functions are designed for posenet and depthnet. If you want to train the flownet, just follow the  command in readme.
