### ISSUE TITLE
About pretrained models

### ISSUE THREAD

**Issue by yuqJin** [guangmingw/DOPlearning#7]
Hi! @guangmingw thanks for your codes.
I can't download the pretrained models, I gauss that it is because the URL cannot be accessed from the external network. Can you give a link that is publicly accessible？

**Comment by zhangciiiii** [comment]
> Hi! @guangmingw thanks for your codes.
> I can't download the pretrained models, I gauss that it is because the URL cannot be accessed from the external network. Can you give a link that is publicly accessible？

you can download the model via this url (https://drive.google.com/file/d/1uaJjeb9qxommZ_AvvRW6Z-mPIeIn2neR/view?usp=sharing);

**Comment by yuqJin** [comment]
> > Hi! @guangmingw thanks for your codes.
> > I can't download the pretrained models, I gauss that it is because the URL cannot be accessed from the external network. Can you give a link that is publicly accessible？
> 
> you can download the model via this url (https://drive.google.com/file/d/1uaJjeb9qxommZ_AvvRW6Z-mPIeIn2neR/view?usp=sharing);

Thank you very much!
